import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  oldTestamentSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🏠 Home',
    },
    {
      type: 'category',
      label: '📖 Old Testament',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Old Testament Books',
        description: 'Study guides for all 39 books of the Old Testament. Add your markdown files here following the structure in the README.',
        slug: '/old-testament',
      },
      items: [
        'old-testament/01-genesis',
        'old-testament/02-exodus',
        'old-testament/03-leviticus',
        'old-testament/04-numbers',
        'old-testament/05-deuteronomy',
        'old-testament/06-joshua',
        'old-testament/07-judges',
        'old-testament/08-ruth',
        'old-testament/09-1-samuel',
        'old-testament/10-2-samuel',
        'old-testament/11-1-kings',
        'old-testament/12-2-kings',
        'old-testament/13-1-chronicles',
        'old-testament/14-2-chronicles',
        'old-testament/15-ezra',
        'old-testament/16-nehemiah',
        'old-testament/17-esther',
        'old-testament/18-job',
        'old-testament/19-psalms',
        'old-testament/20-proverbs',
        'old-testament/21-ecclesiastes',
        'old-testament/22-song-of-solomon',
        'old-testament/23-isaiah',
        'old-testament/24-jeremiah',
        'old-testament/25-lamentations',
        'old-testament/26-ezekiel',
        'old-testament/27-daniel',
        'old-testament/28-hosea',
        'old-testament/29-joel',
        'old-testament/30-amos',
        'old-testament/31-obadiah',
        'old-testament/32-jonah',
        'old-testament/33-micah',
        'old-testament/34-nahum',
        'old-testament/35-habakkuk',
        'old-testament/36-zephaniah',
        'old-testament/37-haggai',
        'old-testament/38-zechariah',
        'old-testament/39-malachi',
      ],
    },
  ],

  newTestamentSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🏠 Home',
    },
    {
      type: 'category',
      label: '📜 New Testament',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'New Testament Books',
        description: 'Study guides for all 27 books of the New Testament',
        slug: '/new-testament',
      },
      items: [
        'new-testament/01-matthew',
        'new-testament/02-mark',
        'new-testament/03-luke',
        'new-testament/04-john',
        'new-testament/05-acts',
        'new-testament/06-romans',
        'new-testament/07-1-corinthians',
        'new-testament/08-2-corinthians',
        'new-testament/09-galatians',
        'new-testament/10-ephesians',
        'new-testament/11-philippians',
        'new-testament/12-colossians',
        'new-testament/13-1-thessalonians',
        'new-testament/14-2-thessalonians',
        'new-testament/15-1-timothy',
        'new-testament/16-2-timothy',
        'new-testament/17-titus',
        'new-testament/18-philemon',
        'new-testament/19-hebrews',
        'new-testament/20-james',
        'new-testament/21-1-peter',
        'new-testament/22-2-peter',
        'new-testament/23-1-john',
        'new-testament/24-2-john',
        'new-testament/25-3-john',
        'new-testament/26-jude',
        'new-testament/27-revelation',
      ],
    },
  ],

  resourcesSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🏠 Home',
    },
    {
      type: 'category',
      label: '📚 Resources & Study Tools',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Study Resources',
        description: 'Comprehensive Bible study tools, indexes, and reference materials. Copy your resource files from the GitHub repo following the README instructions.',
        slug: '/resources',
      },
      items: [
        'resources/maps',
        'resources/printing-guide',
        'resources/copyright-permissions',
        'indexes/character-index',
        'indexes/thematic-index',
        'quick-reference/new-testament-overview',
        'quick-reference/old-testament-overview',
      ],
    },
  ],
};

export default sidebars;
